#!/usr/bin/env bash
export NVM_DIR="$HOME/.nvm"

function _source_nvm() {
  if [ -z "$NVM_PATH" ] ; then
    # Prevent infinite recursion
    unset -f nvm;
    unset -f npm;
    unset -f grunt;
    unset -f yarn;
    . /usr/local/opt/nvm/nvm.sh;
    nvm use v8.1.4
  fi
}

function nvm() {
  _source_nvm
  nvm "$@"
}

function grunt() {
  _source_nvm
  grunt "$@"
}

function npm() {
  _source_nvm
  npm "$@"
}

function yarn() {
  _source_nvm
  yarn "$@"
}

alias grunt="grunt --stack"

# Force nvm to load in non-interactive shells
[[ $- == *i* ]] && true || _source_nvm
